CREATE TABLE players (
    player_id SERIAL PRIMARY KEY,
    shirt_name VARCHAR(30) DEFAULT NULL,
    national VARCHAR(30) DEFAULT NULL,
    name_in_home_country VARCHAR(100) DEFAULT NULL,
    place_of_birth VARCHAR(50) DEFAULT NULL,
    citizenship VARCHAR(50) DEFAULT NULL,
    date_of_birth DATE DEFAULT NULL,
    age INT DEFAULT 0,
    current_club VARCHAR(50) DEFAULT NULL,
    shirt_num INT DEFAULT 0,
    joined DATE DEFAULT NULL,
    contract_expires DATE DEFAULT NULL,
    date_of_last_contract_extension DATE DEFAULT NULL,
    contract_option VARCHAR(50) DEFAULT NULL,
    on_loan_from VARCHAR(50) DEFAULT NULL,
    height INT DEFAULT 0,
    foot VARCHAR(10) DEFAULT NULL,
    position VARCHAR(50) DEFAULT NULL,
    market_value VARCHAR(10) DEFAULT NULL,
    player_agent VARCHAR(50) DEFAULT NULL,
    timestamp TIMESTAMP, 
    url VARCHAR(100) DEFAULT NULL
);

CREATE TABLE players_history (
    _id VARCHAR(24) PRIMARY KEY,
    player_id INT,
    shirt_name VARCHAR(30) DEFAULT NULL,
    national VARCHAR(30) DEFAULT NULL,
    name_in_home_country VARCHAR(100) DEFAULT NULL,
    place_of_birth VARCHAR(50) DEFAULT NULL,
    citizenship VARCHAR(50) DEFAULT NULL,
    date_of_birth DATE DEFAULT NULL,
    age INT DEFAULT 0,
    current_club VARCHAR(50) DEFAULT NULL,
    shirt_num INT DEFAULT 0,
    joined DATE DEFAULT NULL,
    contract_expires DATE DEFAULT NULL,
    date_of_last_contract_extension DATE DEFAULT NULL,
    contract_option VARCHAR(50) DEFAULT NULL,
    on_loan_from VARCHAR(50) DEFAULT NULL,
    height INT DEFAULT 0,
    foot VARCHAR(10) DEFAULT NULL,
    position VARCHAR(50) DEFAULT NULL,
    market_value VARCHAR(10) DEFAULT NULL,
    player_agent VARCHAR(50) DEFAULT NULL,
    timestamp TIMESTAMP, 
    url VARCHAR(100) DEFAULT NULL
);

CREATE TABLE clubs (
    club_id SERIAL PRIMARY KEY,
    club_name VARCHAR(100),
    league VARCHAR(100),
    timestamp TIMESTAMP,
    url VARCHAR(100)
);

CREATE TABLE clubs_history (
    _id VARCHAR(24) PRIMARY KEY,
    club_id SERIAL,
    club_name VARCHAR(100),
    league VARCHAR(100),
    timestamp TIMESTAMP,
    url VARCHAR(100)
);


CREATE TABLE game_stats (
    _id VARCHAR(24) PRIMARY KEY,
    player_id INT REFERENCES players(player_id),
    club_id INT REFERENCES clubs(club_id),
    match_club_id INT REFERENCES clubs(club_id),
    name VARCHAR(30),
    club VARCHAR(100),
    position VARCHAR(10),
    shirt_number INTEGER,
    play_time INTEGER,
    goals INTEGER,
    assists INTEGER,
    total_shots INTEGER,
    shots_on_target INTEGER,
    blocked_shots INTEGER,
    shots_off_target INTEGER,
    shots_inside_box INTEGER,
    shots_outside_box INTEGER,
    offsides INTEGER,
    free_kick INTEGER,
    corners INTEGER,
    throws INTEGER,
    dribbles INTEGER,
    successful_dribble INTEGER,
    successful_dribble_percent DECIMAL(5, 2),
    passes INTEGER,
    successful_passes INTEGER,
    successful_passes_percent DECIMAL(5, 2),
    key_passes INTEGER,
    forward_passes INTEGER,
    successful_forward_passes INTEGER,
    successful_forward_passes_percent DECIMAL(5, 2),
    backward_passes INTEGER,
    successful_backward_passes INTEGER,
    successful_backward_passes_percent DECIMAL(5, 2),
    lateral_passes INTEGER,
    successful_lateral_passes INTEGER,
    successful_lateral_passes_percent DECIMAL(5, 2),
    opposition_half_passes INTEGER,
    successful_opposition_half_passes INTEGER,
    successful_opposition_half_passes_percent DECIMAL(5, 2),
    own_half_passes INTEGER,
    successful_own_half_passes INTEGER,
    successful_own_half_passes_percent DECIMAL(5, 2),
    center_half_passes INTEGER,
    successful_center_half_passes INTEGER,
    successful_center_half_passes_percent DECIMAL(5, 2),
    long_passes INTEGER,
    successful_long_passes INTEGER,
    successful_long_passes_percent DECIMAL(5, 2),
    middle_distance_passes INTEGER,
    successful_middle_distance_passes INTEGER,
    successful_middle_distance_passes_percent DECIMAL(5, 2),
    short_passes INTEGER,
    successful_short_passes INTEGER,
    successful_short_passes_percent DECIMAL(5, 2),
    crosses INTEGER,
    successful_corosses INTEGER,
    successful_corosses_percent DECIMAL(5, 2),
    decompresses INTEGER,
    ground_duel INTEGER,
    ground_duel_won INTEGER,
    ground_duel_won_percent DECIMAL(5, 2),
    aerial_duel INTEGER,
    aerial_duel_won INTEGER,
    aerial_duel_won_percent DECIMAL(5, 2),
    tackles INTEGER,
    tackles_won INTEGER,
    tackles_won_percent DECIMAL(5, 2),
    clearances INTEGER,
    interceptions INTEGER,
    defensive_actions INTEGER,
    recoveries INTEGER,
    block INTEGER,
    dispossessed INTEGER,
    was_fouled INTEGER,
    fouls_commited INTEGER,
    yellow_card INTEGER,
    red_card INTEGER,
    season INTEGER,
    round INTEGER,
    match VARCHAR(100),
    home_away VARCHAR(10),
    competition VARCHAR(100),
    result VARCHAR(5)
);
