CREATE TABLE players (
    player_id SERIAL PRIMARY KEY,
    citizenship VARCHAR(50) DEFAULT NULL,
    contract_expires DATE DEFAULT NULL,
    current_club VARCHAR(50) DEFAULT NULL,
    date_of_birth DATE DEFAULT NULL,
    age INT DEFAULT 0,
    foot VARCHAR(10) DEFAULT NULL,
    height INT DEFAULT 0,
    joined DATE DEFAULT NULL,
    name_in_home_country VARCHAR(50) DEFAULT NULL,
    place_of_birth VARCHAR(50) DEFAULT NULL,
    player_agent VARCHAR(30) DEFAULT NULL,
    position VARCHAR(50) DEFAULT NULL,
    market_value VARCHAR(10) DEFAULT NULL,
    national VARCHAR(30) DEFAULT NULL,
    shirt_name VARCHAR(30) DEFAULT NULL,
    shirt_num INT DEFAULT 0,
    url VARCHAR(100) DEFAULT NULL
    -- Other player-related columns
);

CREATE TABLE clubs (
    club_id SERIAL PRIMARY KEY,
    club_name VARCHAR(100),
    league VARCHAR(100),
    url VARCHAR(100)
    -- Other club-related columns
);


CREATE TABLE player_stats (
    _id VARCHAR(24) PRIMARY KEY,
    player_id INT REFERENCES players(player_id),
    club_id INT REFERENCES clubs(club_id),
    match_club_id INT REFERENCES clubs(club_id),
    successful_lateral_passes_percent DECIMAL(5, 2),
    shots_outside_box INTEGER,
    shots_off_target INTEGER,
    successful_lateral_passes INTEGER,
    short_passes INTEGER,
    blocked_shots INTEGER,
    ground_duel_won INTEGER,
    competition VARCHAR(255),
    aerial_duel_won_percent DECIMAL(5, 2),
    successful_dribble INTEGER,
    crosses INTEGER,
    middle_distance_passes INTEGER,
    shots_inside_box INTEGER,
    successful_backward_passes INTEGER,
    successful_dribble_percent DECIMAL(5, 2),
    club VARCHAR(255),
    season INTEGER,
    block INTEGER,
    tackles INTEGER,
    center_half_passes INTEGER,
    ground_duel_won_percent DECIMAL(5, 2),
    successful_opposition_half_passes INTEGER,
    goals INTEGER,
    offsides INTEGER,
    free_kick INTEGER,
    successful_center_half_passes_percent DECIMAL(5, 2),
    aerial_duel_won INTEGER,
    dribbles INTEGER,
    lateral_passes INTEGER,
    throws INTEGER,
    shirt_number INTEGER,
    successful_center_half_passes INTEGER,
    own_half_passes INTEGER,
    successful_passes INTEGER,
    successful_passes_percent DECIMAL(5, 2),
    aerial_duel INTEGER,
    name VARCHAR(255),
    successful_corosses_percent DECIMAL(5, 2),
    shots_on_target INTEGER,
    successful_long_passes INTEGER,
    tackles_won INTEGER,
    position VARCHAR(255),
    successful_middle_distance_passes INTEGER,
    clearances INTEGER,
    match VARCHAR(255),
    home_away VARCHAR(255),
    yellow_card INTEGER,
    decompresses INTEGER,
    successful_own_half_passes INTEGER,
    long_passes INTEGER,
    forward_passes INTEGER,
    recoveries INTEGER,
    corners INTEGER,
    successful_opposition_half_passes_percent DECIMAL(5, 2),
    successful_short_passes INTEGER,
    passes INTEGER,
    defensive_actions INTEGER,
    fouls_commited INTEGER,
    assists INTEGER,
    successful_backward_passes_percent DECIMAL(5, 2),
    red_card INTEGER,
    play_time_min VARCHAR(255),
    successful_forward_passes_percent DECIMAL(5, 2),
    was_fouled INTEGER,
    successful_own_half_passes_percent DECIMAL(5, 2),
    key_passes INTEGER,
    successful_middle_distance_passes_percent DECIMAL(5, 2),
    opposition_half_passes INTEGER,
    dispossessed INTEGER,
    successful_long_passes_percent DECIMAL(5, 2),
    successful_forward_passes INTEGER,
    total_shots INTEGER,
    successful_short_passes_percent DECIMAL(5, 2),
    interceptions INTEGER,
    tackles_won_percent DECIMAL(5, 2),
    successful_corosses INTEGER,
    round VARCHAR(255),
    ground_duel INTEGER,
    backward_passes INTEGER
);
